title : My Mind to Your Mind
tagline: My Thoughts to Your Thoughts
author :
  name : John Nilsson
  email : john@milsson.nu
  github : JohnNilsson
  twitter : CuriousSkeptic

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
